
services:
  api:
    build: ./backend
    container_name: adotau_api
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/adotau_api
    command: uvicorn adotau_api.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    container_name: adotau_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1013
      POSTGRES_DB: adotau
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
